### ISSUE TITLE
The "replace" link not rendered as a drop-button and also placed outside the "Operations" column.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/title#6]
![backdrop-contrib-title-replace_link_rendered_outside_the_operations_column](https://cloud.githubusercontent.com/assets/2423362/18979276/c2e3a092-870c-11e6-8870-6d26641036d8.png)

**Comment by serundeputy** [comment]
Thanks for reporting @klonos!  Here is what I've found so far.

I can give it the correct markup to render as a drop button, but the `Node module element` `td` element is being rendered with `colspan="2"` which is coming from core ... and I've not figured out how to override it.

here is the markup:

``` html
<td colspan="2">Node module element</td>
```

If we remove the `colspan="2"` from the markup everything falls in line:

![screen shot 2016-10-02 at 10 18 42 am](https://cloud.githubusercontent.com/assets/6763671/19021175/d5963690-8889-11e6-8c22-f2dc82b1d569.png)

We need to override from `title` module itself so that we do not affect users who do not use `title`.

**Comment by serundeputy** [comment]
Got some help in gitter.
merging https://github.com/backdrop-contrib/title/pull/7

thanks!

**Comment by klonos** [comment]
> If we remove the `colspan="2"` from the markup everything falls in line:

Yes, I know 😕 

> Got some help in gitter.

Hey, I think that this is very similar to the side-effect issue I bumped into in https://github.com/backdrop/backdrop-issues/issues/1931#issuecomment-221782030 while trying to solve the main issue there. I couldn't figure it out, but I did file a follow-up in https://github.com/backdrop/backdrop-issues/issues/1932
Might give it a second go then 😉 ...when I find time (joke, haha).
